version: '2'
services:
  web:
    build: ./web
    command: bash -c "cat /web/cron.config >> /etc/crontab && uwsgi --socket marco1.sock --module marco.wsgi --chmod-socket=666"
      #-
    volumes:
      - ./web:/web
      - ./media:/media
      - ./static:/static
      - ./log:/log
      - ./backup:/backup
    ports:
      - "8000:8000"
    depends_on:
      - db
      - memcached


  db:
    image: mysql
    volumes:
      - ./mysql/storage/:/var/lib/mysql
      - ./mysql/conf.cnf:/etc/mysql/conf.d/mysql_conf.cnf
    environment:
      MYSQL_DATABASE: marco_db
      MYSQL_USER: VLAD
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root

    ports:
      - "3308:3306"

  nginx:
    image: xdrum/nginx-extras
    ports:
     - "80:80"
    volumes:
     - ./frontend:/frontend
     - ./nginx/default:/etc/nginx/conf.d/default.conf
     - ./nginx/cache:/var/nginx/cache
    volumes_from:
     - web
    links:
     - web:web
     - memcached:memcached

  memcached:
    image: memcached
    ports:
      - "11211:11211"




