# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255, unique=True)),
                ('enabled', models.BooleanField()),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='api.Category', verbose_name='Родитель')),
            ],
            options={
                'verbose_name_plural': 'Категории',
                'verbose_name': 'Категория',
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(upload_to='product/img/%Y/%m/%d/')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name_plural': 'Изображения',
                'verbose_name': 'Изображение',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Новый'), (1, 'Упаковка'), (2, 'Отменненый'), (3, 'Доставка'), (4, 'Ждет оплаты'), (5, 'Выполненый'), (6, 'Изготовление')], default=0, verbose_name='Статус')),
                ('delivery_method', models.IntegerField(choices=[(0, 'Самовывоз'), (1, 'Новая Почта'), (2, 'Укрпочта')], default=0, verbose_name='Способ доставки')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к заказу')),
                ('comment_admin', models.TextField(blank=True, null=True, verbose_name='Комментарий продавца')),
            ],
            options={
                'verbose_name_plural': 'Заказы',
                'verbose_name': 'Заказ',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('url', models.CharField(max_length=255, unique=True, verbose_name='Транслитерация')),
                ('description', models.TextField(blank=True, verbose_name='Описание товара')),
                ('_title_image', models.ImageField(upload_to='product/img/%Y/%m/%d/', verbose_name='Главное изображение')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('enabled', models.BooleanField(verbose_name='Активный')),
                ('time_add', models.DateTimeField(auto_now_add=True)),
                ('is_new', models.BooleanField(verbose_name='Новинка')),
                ('is_preorder', models.BooleanField(verbose_name='Предзаказ')),
                ('is_sale', models.BooleanField(verbose_name='Отображать акции')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='api.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name_plural': 'Товары',
                'verbose_name': 'Товар',
            },
        ),
        migrations.CreateModel(
            name='ProductSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='sale/img/%Y/%m/%d/', verbose_name='Изображение')),
                ('time_start', models.DateTimeField(blank=True, verbose_name='Дата старта')),
                ('time_end', models.DateTimeField(blank=True, verbose_name='Дата конца')),
            ],
            options={
                'verbose_name_plural': 'Акции',
                'verbose_name': 'Акция',
            },
        ),
        migrations.CreateModel(
            name='SeoBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Сео Название')),
                ('meta', models.CharField(max_length=255, verbose_name='СЕО мета тег')),
                ('description', models.TextField(verbose_name='СЕО описание')),
            ],
            options={
                'verbose_name_plural': 'SEO блоки',
                'verbose_name': 'SEO блок',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('enabled', models.BooleanField(verbose_name='Активный')),
            ],
            options={
                'verbose_name_plural': 'Слайдер',
                'verbose_name': 'Cлайдер',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
            ],
            options={
                'verbose_name_plural': 'Пользователи',
                'verbose_name': 'Пользователь',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='sales',
            field=models.ManyToManyField(blank=True, related_name='sale_pk', to='api.Sale', verbose_name='Акции'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo', to='api.SeoBlock', verbose_name='Сео блок'),
        ),
        migrations.AddField(
            model_name='order',
            name='product_set',
            field=models.ManyToManyField(through='api.ProductSet', to='api.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_user_pk', to='api.User', verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.SeoBlock', verbose_name='Сео блок'),
        ),
    ]
