# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('enabled', models.BooleanField()),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='api.Category', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(upload_to='product/img/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('url', models.CharField(max_length=255, verbose_name='Транслитерация')),
                ('description', models.TextField(blank=True, verbose_name='СЕО описание')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('enabled', models.BooleanField(verbose_name='Активный')),
                ('time_add', models.DateTimeField(auto_now_add=True)),
                ('is_new', models.BooleanField(verbose_name='Новинка')),
                ('is_preorder', models.BooleanField(verbose_name='Предзаказ')),
                ('is_sale', models.BooleanField(verbose_name='Отображать акции')),
                ('_gallery', models.ManyToManyField(blank=True, related_name='gallery', to='api.Image', verbose_name='Изображения')),
                ('_title_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Image', verbose_name='Главное изображение')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='api.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('time_start', models.DateTimeField(blank=True, verbose_name='Дата старта')),
                ('time_end', models.DateTimeField(blank=True, verbose_name='Дата конца')),
                ('_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Image', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.CreateModel(
            name='SeoBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Сео Название')),
                ('meta', models.CharField(max_length=255, verbose_name='СЕО мета тег')),
                ('description', models.TextField(verbose_name='СЕО описание')),
            ],
            options={
                'verbose_name': 'SEO блок',
                'verbose_name_plural': 'SEO блоки',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('enabled', models.BooleanField(verbose_name='Активный')),
                ('gallery', models.ManyToManyField(blank=True, related_name='gallery_pk', to='api.Image', verbose_name='Изображения 800x400')),
            ],
            options={
                'verbose_name': 'Cлайдер',
                'verbose_name_plural': 'Слайдер',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='sales',
            field=models.ManyToManyField(blank=True, related_name='sale_pk', to='api.Sale', verbose_name='Акции'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo', to='api.SeoBlock', verbose_name='Сео блок'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.SeoBlock', verbose_name='Сео блок'),
        ),
    ]
