# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('enabled', models.BooleanField()),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='api.Category', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(upload_to='api/static/img/%Y/%m/%d/')),
                ('thumb', models.ImageField(upload_to='api/static/img/%Y/%m/%d/thumb/')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Иображения',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('url', models.CharField(max_length=255, verbose_name='Транслитерация')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('enabled', models.BooleanField(verbose_name='Активный')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='api.Category', verbose_name='Категория')),
                ('gallery', models.ManyToManyField(blank=True, related_name='gallery', to='api.Image', verbose_name='Изображения')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='SeoBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Сео Название')),
                ('meta', models.CharField(max_length=255, verbose_name='СЕО мета тег')),
                ('description', models.TextField(verbose_name='СЕО описание')),
            ],
            options={
                'verbose_name': 'SEO блок',
                'verbose_name_plural': 'SEO блоки',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='seo_block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo', to='api.SeoBlock', verbose_name='Сео блок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Image', verbose_name='Главное изображение'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.SeoBlock', verbose_name='Сео блок'),
        ),
    ]
