# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 06:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(upload_to='img/%Y/%m/%d/')),
                ('thumb', models.ImageField(upload_to='img/%Y/%m/%d/thumb/')),
            ],
            options={
                'verbose_name_plural': 'Иображения',
                'verbose_name': 'Изображение',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('enabled', models.BooleanField(verbose_name='Активный')),
            ],
            options={
                'verbose_name_plural': 'Слайдер',
                'verbose_name': 'Cлайдер',
            },
        ),
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(upload_to='img/%Y/%m/%d/')),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name_plural': 'Изображение для Слайдера',
                'verbose_name': 'Изображение для Слайдера',
            },
        ),
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='api.Category', verbose_name='Родитель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='gallery', to='api.ProductImage', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ProductImage', verbose_name='Главное изображение'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='slider',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='gallery', to='api.SliderImage', verbose_name='Изображения 800x300'),
        ),
    ]
