# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='_gallery',
            new_name='gallery',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='_title_image',
            new_name='title_image',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='_image',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(max_length=255, unique=True, verbose_name='Транслитерация'),
        ),
    ]
