# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumb',
            field=models.ImageField(upload_to='img/%Y/%m/%d/thumb/'),
        ),
    ]
