# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0001_initial'),
    ]

    operations = [


        migrations.AddField(
            model_name='seoblock',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seoblock',
            name='keywords',
            field=models.TextField(default=1, max_length=255, verbose_name='Ключевые слова страницы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seoblock',
            name='meta_description',
            field=models.CharField(default=1, max_length=255, verbose_name='Мета описание СЕО'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seoblock',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seoblock',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='seoblock',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок СЕО'),
        ),
    ]
