# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 05:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160525_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='seo_block',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seo_block',
        ),
        migrations.RemoveField(
            model_name='seoblock',
            name='meta',
        ),
    ]
