# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160422_0616'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(upload_to='img/%Y/%m/%d/')),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Изображение для Слайдера',
                'verbose_name_plural': 'Изображение для Слайдера',
            },
        ),
        migrations.RenameModel(
            old_name='Image',
            new_name='ProductImage',
        ),
    ]
