# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160422_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('enabled', models.BooleanField(verbose_name='Активный')),
                ('gallery', models.ManyToManyField(blank=True, related_name='gallery', to='api.SliderImage', verbose_name='Изображения 800x300')),
            ],
            options={
                'verbose_name_plural': 'Слайдер',
                'verbose_name': 'Cлайдер',
            },
        ),
    ]
