# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 07:54
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import django.db.models.manager
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_slider'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='api.Category', verbose_name='Родитель'),
        ),
    ]
