# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160520_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Новый'), (1, 'Упаковка'), (2, 'Отменненый'), (3, 'Доставка'), (4, 'Ждет оплаты'), (5, 'Выполненый'), (6, 'Изготовление')], default=0, max_length=1, verbose_name='Статус'),
        ),
    ]
