# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 09:27
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20160423_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='api.Category', verbose_name='Родитель'),
        ),
    ]
