# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20160520_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_set',
            field=models.ManyToManyField(through='api.ProductSet', to='api.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Новый'), (1, 'Упаковка'), (2, 'Отменненый'), (3, 'Доставка'), (4, 'Ждет оплаты'), (5, 'Выполненый'), (6, 'Изготовление')], default=0, verbose_name='Статус'),
        ),
    ]
