# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20160520_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к заказу'),
        ),
        migrations.AddField(
            model_name='order',
            name='comment_admin',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий продавца'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.IntegerField(choices=[(0, 'Самовывоз'), (1, 'Новая Почта'), (2, 'Укрпочта')], default=0, verbose_name='Способ доставки'),
        ),
    ]
