# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20160525_0625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gallery',
        ),
        migrations.AddField(
            model_name='product',
            name='title_image',
            field=models.ImageField(default=1, upload_to='product/img/%Y/%m/%d/', verbose_name='Главное изображение'),
            preserve_default=False,
        ),
    ]
