# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20160525_0631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title_image',
            new_name='_title_image',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание товара'),
        ),
    ]
