# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20160525_0648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='gallery',
        ),
        migrations.AlterField(
            model_name='sale',
            name='image',
            field=models.ImageField(default=1, upload_to='sale/img/%Y/%m/%d/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
